replicaCount: 1

image:
  repository: alpine
  pullPolicy: IfNotPresent
  tag: ""  # defaults to appVersion (3)

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534   # nobody
  runAsGroup: 65534
  fsGroup: 65534
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

command: ["sleep"]
args: ["infinity"]

resources:
  limits:
    cpu: 50m
    memory: 32Mi
  requests:
    cpu: 5m
    memory: 8Mi

nodeSelector: {}
tolerations: []
affinity: {}
