apiVersion: v1
kind: Service
metadata:
  name: {{ include "toxiproxy.fullname" . }}
  labels:
    {{- include "toxiproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "toxiproxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
    {{- range .Values.proxies }}
    - name: {{ .name | trunc 15 | trimSuffix "-" }}
      port: {{ regexFind "[0-9]+$" .listen | int }}
      targetPort: {{ .name | trunc 15 | trimSuffix "-" }}
      protocol: TCP
    {{- end }}
