{{- if eq .Values.workloadType "job" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "trivy.fullname" . }}
  labels:
    {{- include "trivy.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  {{- if .Values.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "trivy.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "trivy.podSpec" . | nindent 6 }}
{{- end }}
