apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trivy-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trivy-operator.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "trivy-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trivy-operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "trivy-operator.serviceAccountName" . }}
      automountServiceAccountToken: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: trivy-operator
          image: {{ include "trivy-operator.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OPERATOR_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: OPERATOR_TARGET_NAMESPACES
              value: {{ .Values.targetNamespaces | quote }}
            - name: OPERATOR_EXCLUDE_NAMESPACES
              value: {{ .Values.excludeNamespaces | quote }}
            - name: OPERATOR_TARGET_WORKLOADS
              value: {{ .Values.targetWorkloads | quote }}
            - name: OPERATOR_SERVICE_ACCOUNT
              value: {{ include "trivy-operator.serviceAccountName" . | quote }}
          envFrom:
            - configMapRef:
                name: trivy-operator-config
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: probes
              containerPort: 9090
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz/
              port: probes
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz/
              port: probes
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
